### ISSUE TITLE
Add permissions for users/clients

### ISSUE THREAD

**Issue by PascalPencil** [Superpencil/Superpencil#19]
I’ve reached my limit and need some help

I need to:
- [X] allow certain users to see certain clients (and by extension their projects)
- [X] allow only logged-in users to create, edit, etc articles, while non-logged in users can still view them and see index
- [x] to have people only able to sign up by invitation

Devise is working and running, the repo is Superpencil/Superpencil and the branch is #devise

**Comment by mvaneyken** [comment]
Changes are in the admin branch; more to come.

**Comment by PascalPencil** [comment]
@mvaneyken for now all we need:
- [ ] sign-ups only by invitation
- [ ] a way for these new signups to be able to view only a single client (and related projects)

**Comment by PascalPencil** [comment]
@mvaneyken
let's not do invitation, too hard, lets just make a new model that takes account creation out of the public domain and makes it something only god can do (devise will complain we are already logged in)
I found a tutorial on it but I couldn't manage it: 

**To implement the authorization, use a method on the controller**

```
class UsersController < ApplicationController
  before_filter :authorize_admin, only: :create

  def create
    # admins only
  end

  private

  # This should probably be abstracted to ApplicationController
  # as shown by diego.greyrobot
  def authorize_admin
    return unless !current_user.admin?
    redirect_to root_path, alert: 'Admins only!'
  end
end
```
To sidestep the Devise 'already logged in' problem, define a new route for creating users.

We will simply define a new route to handle the creation of users and then point the form to that location. This way, the form submission does not pass through the devise controller so you can feel free to use it anywhere you want in the normal Rails way.
```
# routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, except: :create

  # Name it however you want
  post 'create_user' => 'users#create', as: :create_user      

end

# users/new.html.erb
# notice the url argument
<%= form_for User.new, url: create_user_path do |f| %>
  # The form content
<% end %>
```
