### ISSUE TITLE
Can't turn on/off Godly on users

### ISSUE THREAD

**Issue by PascalPencil** [Superpencil/Superpencil#24]
When editing users as a Diety, I can't turn off or on their Godliness

**Comment by PascalPencil** [comment]
And I need to input their password to make changes

**Comment by mvaneyken** [comment]
@PascalPencil 
Actually both issues are interrelated. To update any of the user fields we were forced to type in the password (two times). I've solved the problem by splitting the screen into two forms. The first form is for any user fields. The second is for the password changes.
